uploads = []
generated = []

[[outputs]]
id = "IZVCTWBsnGRkGIKneljT0"
uri = "file://book-fairies-website.tar.gz"
type = "unspecified"
title = "Book Fairies — HTML Export"

[[outputs]]
id = "Anmv_bbqOGs3l4iH8wKx4"
uri = "file://book-fairies-github.tar.gz"
type = "unspecified"
title = "Book Fairies — GitHub Pages Files"

[[outputs]]
id = "eGF6F8aGzJt0EGu9Qof41"
uri = "file://book-fairies-website.zip"
type = "unspecified"
title = "Book Fairies Website — bookfairiesga"

[[outputs]]
id = "yn0cjlU5AQGTA1-Z1yItb"
uri = "file://artifacts/book-fairies/dist/public/index.html"
type = "unspecified"
title = "index.html — Book Fairies"
